modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="craftingconvenience"
version="1.0.0"
displayName="CraftingConvenience"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator"
description="The mod to make crafting convenient"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.craftingconvenience]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration